import Foundation
import vevc

func printStaticRANSModelsCode(trainer: ModelTrainer) {
    print("    // Generated by vevc-training")
    
    for ctx in 0..<4 {
        print("    static let runModel\(ctx) = rANSModel(")
        print("        frequencies: [")
        var runTokens = [String]()
        for i in 0..<64 {
            let count = max(1, trainer.runFreqs[ctx][i])
            runTokens.append("\(count)")
        }
        for chunk in runTokens.chunked(into: 16) {
            print("            " + chunk.joined(separator: ", ") + ",")
        }
        print("        ],")
        print("        scaleBits: 14")
        print("    )")
        print()
        
        print("    static let valModel\(ctx) = rANSModel(")
        print("        frequencies: [")
        var valTokens = [String]()
        for i in 0..<64 {
            let count = max(1, trainer.valFreqs[ctx][i])
            valTokens.append("\(count)")
        }
        for chunk in valTokens.chunked(into: 16) {
            print("            " + chunk.joined(separator: ", ") + ",")
        }
        print("        ],")
        print("        scaleBits: 14")
        print("    )")
        print()
    }
}

extension Array {
    func chunked(into size: Int) -> [[Element]] {
        return stride(from: 0, to: count, by: size).map {
            Array(self[$0 ..< Swift.min($0 + size, count)])
        }
    }
}

func main() async {
    let args = CommandLine.arguments
    if args.count < 2 {
        print("Usage: vevc-training <input1.y4m> [<input2.y4m> ...]")
        exit(1)
    }
    
    let y4mPaths = args.dropFirst()
    
    // Enable collection in EntropyEncoder
    ModelTrainer.shared.isTrainingMode = true
    ModelTrainer.shared.reset()
    
    for path in y4mPaths {
        guard let fileHandle = FileHandle(forReadingAtPath: String(path)) else {
            print("Failed to open file: \(path)")
            continue
        }
        
        print("Processing \(path)...")
        guard let reader = try? Y4MReader(fileHandle: fileHandle) else {
            print("Failed to read y4m header: \(path)")
            continue
        }
        
        var images = [YCbCrImage]()
        while let frameData = try? reader.readFrame() {
            images.append(frameData)
        }
        
        print("Loaded \(images.count) frames from \(path)")
        
        let encoder = VEVCEncoder(
            width: reader.width,
            height: reader.height,
            maxbitrate: 1000,
            framerate: 60,
            zeroThreshold: 0,
            keyint: 60,
            sceneChangeThreshold: 1000,
            maxConcurrency: 1
        )
        
        do {
            let _ = try await encoder.encodeToData(images: images)
            print("Encoded \(path) and collected frequencies.")
        } catch {
            print("Failed to encode \(path): \(error)")
        }
    }
    
    // Disable collection
    ModelTrainer.shared.isTrainingMode = false
    
    let trainer = ModelTrainer.shared
    
    // Normalize and scale frequencies
    let scaleBits = 14
    let targetTotal = UInt32(1 << scaleBits)
    
    for ctx in 0..<4 {
        // Run Model
        let runTotal = trainer.runFreqs[ctx].reduce(0, +)
        if runTotal > 0 {
            for i in 0..<64 {
                let scaled = UInt32(UInt64(trainer.runFreqs[ctx][i]) * UInt64(targetTotal) / UInt64(runTotal))
                trainer.runFreqs[ctx][i] = max(1, scaled) // Ensure at least 1
            }
        }
        
        // Val Model
        let valTotal = trainer.valFreqs[ctx].reduce(0, +)
        if valTotal > 0 {
            for i in 0..<64 {
                let scaled = UInt32(UInt64(trainer.valFreqs[ctx][i]) * UInt64(targetTotal) / UInt64(valTotal))
                trainer.valFreqs[ctx][i] = max(1, scaled)
            }
        }
    }
    
    print("\n\n=== Generated Static RANS Models ===\n")
    printStaticRANSModelsCode(trainer: trainer)
}

await main()
