import Foundation
import vevc

public struct TrainConfig {
    public var epochs: Int = 10
    public var lr: Float = 0.005
    public var batchSize: Int = 16
    public var numPatches: Int = 256
    public var patchSize: Int = 32
    public var dryRun: Bool = false
    public var exportPath: String = "Sources/vevc/SNNWeights.swift"
    public var inputY4M: String? = nil
}

func parseCommandLineArgs() -> TrainConfig {
    var config = TrainConfig()
    let args = CommandLine.arguments

    var idx = 1
    while idx < args.count {
        let arg = args[idx]
        switch arg {
        case "--epochs":
            if idx + 1 < args.count {
                config.epochs = Int(args[idx + 1]) ?? 10
                idx &+= 1
            }
        case "--lr":
            if idx + 1 < args.count {
                config.lr = Float(args[idx + 1]) ?? 0.005
                idx &+= 1
            }
        case "--batch-size":
            if idx + 1 < args.count {
                config.batchSize = Int(args[idx + 1]) ?? 16
                idx &+= 1
            }
        case "--patches":
            if idx + 1 < args.count {
                config.numPatches = Int(args[idx + 1]) ?? 256
                idx &+= 1
            }
        case "--patch-size":
            if idx + 1 < args.count {
                config.patchSize = Int(args[idx + 1]) ?? 32
                idx &+= 1
            }
        case "--dry-run":
            config.dryRun = true
        case "--export-swift-tables":
            if idx + 1 < args.count {
                config.exportPath = args[idx + 1]
                idx &+= 1
            }
        case "--input-y4m":
            if idx + 1 < args.count {
                config.inputY4M = args[idx + 1]
                idx &+= 1
            }
        default:
            break
        }
        idx &+= 1
    }

    if config.dryRun {
        config.epochs = 1
        config.numPatches = 16
        config.batchSize = 4
    }

    return config
}

public func generateSwiftWeightTablesCode(params: SNNModelParams) -> String {
    // Quantize Conv1 weights to Q7 (Int8)
    let conv1Q7: [Int8] = params.w1.map { val in
        let q = Int(roundf(val * 128.0))
        return Int8(max(-128, min(127, q)))
    }
    let conv1BiasesQ11: [Int16] = params.b1.map { val in
        let q = Int(roundf(val * 2048.0))
        return Int16(max(-32768, min(32767, q)))
    }

    // Quantize Conv2 weights to Q7 (Int8)
    let conv2Q7: [Int8] = params.w2.map { val in
        let q = Int(roundf(val * 128.0))
        return Int8(max(-128, min(127, q)))
    }
    let conv2BiasesQ11: [Int16] = params.b2.map { val in
        let q = Int(roundf(val * 2048.0))
        return Int16(max(-32768, min(32767, q)))
    }

    // Quantize Output weights to Q11 (Int16)
    let outWeightsQ11: [Int16] = params.wOut.map { val in
        let q = Int(roundf(val * 2048.0))
        return Int16(max(-32768, min(32767, q)))
    }
    let outBiasQ11: Int16 = {
        let q = Int(roundf(params.bOut[0] * 2048.0))
        return Int16(max(-32768, min(32767, q)))
    }()

    var code = "// Auto-generated SNN Neural Loop Filter Weights and Tables\n"
    code += "// Generated by vevc-snn-train\n"
    code += "import Foundation\n\n"
    code += "public enum SNNWeights {\n"
    code += "    public static let numTimeSteps: Int = 2\n"
    code += "    public static let vThresh1: Int16 = 2048\n"
    code += "    public static let vThresh2: Int16 = 2048\n"
    code += "    public static let leakShift: Int = 2\n\n"

    code += "    /// Conv1 Weights: [8, 4, 3, 3] = 288 Int8 elements (Q7 fixed-point)\n"
    code += "    public static let conv1Weights: [Int8] = [\n"
    for i in 0..<conv1Q7.count {
        code += "        \(conv1Q7[i]),\n"
    }
    code += "    ]\n\n"

    code += "    /// Conv1 Biases: [8] = 8 Int16 elements (Q11 fixed-point)\n"
    code += "    public static let conv1Biases: [Int16] = [\n"
    for i in 0..<conv1BiasesQ11.count {
        code += "        \(conv1BiasesQ11[i]),\n"
    }
    code += "    ]\n\n"

    code += "    /// Conv2 Weights: [8, 8, 1, 1] = 64 Int8 elements (Q7 fixed-point)\n"
    code += "    public static let conv2Weights: [Int8] = [\n"
    for i in 0..<conv2Q7.count {
        code += "        \(conv2Q7[i]),\n"
    }
    code += "    ]\n\n"

    code += "    /// Conv2 Biases: [8] = 8 Int16 elements (Q11 fixed-point)\n"
    code += "    public static let conv2Biases: [Int16] = [\n"
    for i in 0..<conv2BiasesQ11.count {
        code += "        \(conv2BiasesQ11[i]),\n"
    }
    code += "    ]\n\n"

    code += "    /// Output Weights: [8] = 8 Int16 elements (Q11 fixed-point)\n"
    code += "    public static let outWeights: [Int16] = [\n"
    for i in 0..<outWeightsQ11.count {
        code += "        \(outWeightsQ11[i]),\n"
    }
    code += "    ]\n\n"

    code += "    /// Output Bias: 1 Int16 element (Q11 fixed-point)\n"
    code += "    public static let outBias: Int16 = \(outBiasQ11)\n"
    code += "}\n"

    return code
}

func main() {
    let config = parseCommandLineArgs()
    print("=== VEVC SNN Training Framework (vevc-snn-train) ===")
    print("Configuration: epochs=\(config.epochs), lr=\(config.lr), batchSize=\(config.batchSize), patches=\(config.numPatches), dryRun=\(config.dryRun)")

    // 1. Prepare dataset
    var dataset: [TrainingSample] = []
    if let y4m = config.inputY4M {
        print("Loading training patches from Y4M: \(y4m)...")
        do {
            dataset = try DatasetGenerator.extractY4MPatches(y4mPath: y4m, patchSize: config.patchSize, maxPatches: config.numPatches)
        } catch {
            print("Warning: Failed to load Y4M (\(error)), falling back to synthetic dataset.")
            dataset = DatasetGenerator.generateSyntheticDataset(numSamples: config.numPatches, patchSize: config.patchSize)
        }
    } else {
        print("Generating synthetic DWT-compressed training dataset (\(config.numPatches) samples)...")
        dataset = DatasetGenerator.generateSyntheticDataset(numSamples: config.numPatches, patchSize: config.patchSize)
    }
    print("Dataset ready: \(dataset.count) samples of size \(config.patchSize)x\(config.patchSize)")

    // 2. Initialize model and optimizer
    let model = SNNModel(numSteps: 2)
    let optimizer = AdamOptimizer(lr: config.lr, beta1: 0.9, beta2: 0.999, weightDecay: 1e-4, clipNorm: 1.0)
    optimizer.registerParameters(paramShapes: model.params.toParameterArray().map { $0.count })

    var cache = ForwardCache(width: config.patchSize, height: config.patchSize, numSteps: 2)
    var batchGrads = SNNGradients()
    var sampleGrads = SNNGradients()

    // 3. Training Loop
    print("\n--- Starting Training Loop ---")
    for epoch in 1...config.epochs {
        var epochTotalLoss: Float = 0.0
        var epochCharbLoss: Float = 0.0
        var epochSSIMLoss: Float = 0.0
        var numBatches = 0

        var sampleIdx = 0
        while sampleIdx < dataset.count {
            batchGrads.reset()
            let batchEnd = min(dataset.count, sampleIdx + config.batchSize)
            let actualBatchSize = batchEnd - sampleIdx

            var batchLoss: Float = 0.0
            var batchCharb: Float = 0.0
            var batchSSIM: Float = 0.0

            for i in sampleIdx..<batchEnd {
                let sample = dataset[i]
                let pred = model.forward(
                    inputFeatures: sample.inputFeatures,
                    width: sample.width,
                    height: sample.height,
                    cache: &cache
                )

                let spatialCount = sample.width * sample.height
                var lossGrad = [Float](repeating: 0.0, count: spatialCount)
                let lossRes = LossFunctions.computeTotalLoss(
                    pred: pred,
                    target: sample.targetResidual,
                    width: sample.width,
                    height: sample.height,
                    ssimWeight: 0.2,
                    grad: &lossGrad
                )

                batchLoss += lossRes.totalLoss
                batchCharb += lossRes.charbLoss
                batchSSIM += lossRes.ssimLoss

                sampleGrads.reset()
                model.backward(gradOutput: lossGrad, cache: cache, grads: &sampleGrads)

                // Accumulate sample gradients into batch gradients
                let sArr = sampleGrads.toGradientArray()
                var bArr = batchGrads.toGradientArray()
                for p in 0..<bArr.count {
                    for k in 0..<bArr[p].count {
                        bArr[p][k] += sArr[p][k]
                    }
                }
                batchGrads.updateFromGradientArray(bArr)
            }

            // Average gradients over batch
            let invB = 1.0 / Float(max(1, actualBatchSize))
            var finalGrads = batchGrads.toGradientArray()
            for p in 0..<finalGrads.count {
                for k in 0..<finalGrads[p].count {
                    finalGrads[p][k] *= invB
                }
            }

            var paramArr = model.params.toParameterArray()
            optimizer.step(params: &paramArr, grads: &finalGrads)
            model.params.updateFromParameterArray(paramArr)

            epochTotalLoss += batchLoss * invB
            epochCharbLoss += batchCharb * invB
            epochSSIMLoss += batchSSIM * invB
            numBatches &+= 1

            sampleIdx = batchEnd
        }

        let avgTotal = epochTotalLoss / Float(max(1, numBatches))
        let avgCharb = epochCharbLoss / Float(max(1, numBatches))
        let avgSSIM = epochSSIMLoss / Float(max(1, numBatches))
        print("Epoch [\(epoch)/\(config.epochs)] - Loss: \(String(format: "%.6f", avgTotal)) (Charbonnier: \(String(format: "%.6f", avgCharb)), SSIM Proxy: \(String(format: "%.6f", avgSSIM)))")
    }

    // 4. Export static Swift weight tables
    print("\n--- Exporting Static Weights ---")
    let swiftCode = generateSwiftWeightTablesCode(params: model.params)
    let exportURL = URL(fileURLWithPath: config.exportPath)
    do {
        try swiftCode.write(to: exportURL, atomically: true, encoding: .utf8)
        print("Successfully exported static weights to: \(config.exportPath)")
    } catch {
        print("Error: Failed to write static weight tables to \(config.exportPath): \(error)")
    }

    print("vevc-snn-train completed successfully.")
}

main()
